image: docker:19.03.1

services:
  - docker:19.03.1-dind

# before_script:
#   - docker info

build_image:
  script:
    - docker image  build -t zzuligy/online-ppt .
    - docker container run -p 8360:8360 -v $PWD/runtime:/animaris/runtime  zzuligy/online-ppt

    